services:
  - type: web
    name: botityourself-landing
    env: static
    buildCommand: npm install && npm run generate
    staticPublishPath: .output/public
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
